// CATCH_ERROR ACTION TYPES
export const CATCH_ERROR = 'CATCH_ERROR';

// AUTH ACTION TYPES
export const REGISTER_NEW_USER = 'REGISTER_NEW_USER';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

// PROFILE ACTION TYPES
export const GET_PROFILE = 'GET_PROFILE';
export const GET_ALL_PROFILES = 'GET_ALL_PROFILES';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
